version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    reviewers:
      - "d4rkfella"
    assignees:
      - "d4rkfella"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
    labels:
      - "dependencies"
      - "github_actions"