bucket   = "terraform-state"
region   = "auto"
endpoints = { s3 = "https://2bd80478faceecf0d53c596cd910805f.r2.cloudflarestorage.com" }
skip_credentials_validation  = true
skip_metadata_api_check      = true
skip_region_validation       = true
skip_requesting_account_id   = true
use_path_style               = true
