name: Terraform CI

on:
  schedule:
    - cron: '0 0 * * *'   # Run daily at midnight UTC
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  packages: write
  contents: read

jobs:
  discover-terraform-configs:
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.set-matrix.outputs.folders }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - id: set-matrix
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const folders = fs.readdirSync('.').filter(f => fs.statSync(f).isDirectory());
            const imageFolders = folders.filter(f => fs.existsSync(path.join(f, 'main.tf')));
            console.log('Discovered image folders:', imageFolders);
            core.setOutput('folders', JSON.stringify(imageFolders));

  build:
    needs: discover-terraform-configs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder: ${{ fromJSON(needs.discover-terraform-configs.outputs.folders) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_wrapper: false

      - name: Setup QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
      
      - name: Login to GHCR
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Apply
        working-directory: ${{ matrix.folder }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: |
          terraform init -backend-config="../common_backend.conf -backend-config="key=${{ matrix.folder }}/terraform.tfstate""
          terraform apply -auto-approve
