name: Test apko-renovator

on:
  workflow_dispatch: {}
permissions:
  contents: write
  pull-requests: write
  id-token: write
  
jobs:
  renovate-apko:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Renovator
        uses: ./.github/actions/renovate
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          arch: "x86_64,aarch64"
          skip-verify: "true"
          repositories: |
            https://packages.darkfellanetwork.com/artifactory/wolfi-os/latest/main
          keys: |
            https://packages.darkfellanetwork.com/artifactory/wolfi-os/melange.rsa.pub
          workdir: ${{ github.workspace }}
